# Generated by Django 4.2.5 on 2023-09-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
